INSERT INTO `#__jshopping_payment_method` (
	`payment_code`, 
	`payment_class`, 
	`payment_publish`, 
	`payment_ordering`, 
	`payment_type`, 
	`price`, 
	`price_type`, 
	`tax_id`, 
	`show_descr_in_email`, 
	`name_en-GB`,
	`name_de-DE`,
  /*`name_en-US`,*/
  `name_ru-RU`
	) VALUES (
	'Fondy', 
	'pm_fondy', 
	0, 
	0, 
	2, 
	0.00, 
	1, 
	-1, 
	0, 
	'Fondy',
	'Fondy',
  /*'Fondy',*/
  'Fondy'
);